name: Build and upload release artifacts

on:
  release:
    types: [published]

jobs:
  build:
    name: Build artifacts
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: linux-x86_64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: windows-x86_64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install target
        run: rustup target add ${{ matrix.target }}

      - name: Build release
        run: cargo build --manifest-path ./crates/ark-wallet-cli/Cargo.toml --release --target ${{ matrix.target }}

      - name: Create dist directory
        run: mkdir -p dist

      - name: Package Windows artifact
        if: matrix.os == 'windows-latest'
        run: |
          powershell -Command "Compress-Archive -Path target/${{ matrix.target }}/release/ark-wallet.exe -DestinationPath dist/ark-wallet-${{ github.ref_name }}-${{ matrix.artifact_name }}.zip"

      - name: Package Linux artifact
        if: matrix.os == 'ubuntu-latest'
        run: |
          tar -czf dist/ark-wallet-${{ github.ref_name }}-${{ matrix.artifact_name }}.tar.gz -C target/${{ matrix.target }}/release ark-wallet

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
