name: Security scan (cargo-audit + geiger)

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  audit:
    name: cargo-audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain-action@stable
      - name: Install cargo-audit
        run: |
          # Use a recent cargo-audit release
          cargo install cargo-audit --version 0.21.2 || true
      - name: Run cargo audit and save JSON
        run: |
          mkdir -p target/audit
          # Save machine-readable JSON for artifact upload and keep human output in the log
          cargo audit --json > target/audit/audit.json || true
          cargo audit || true
      - name: Upload cargo-audit result
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cargo-audit-report
          path: ./target/audit

  geiger:
    name: cargo-geiger
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain-action@stable
      - name: Install cargo-geiger
        run: |
          cargo install cargo-geiger --version 0.27.0 || true
      - name: Run cargo-geiger (conservative quick check)
        run: |
          cargo geiger --manifest-path crates/ark-wallet-cli/Cargo.toml --forbid-only --output geiger-ark-wallet-cli.txt || true
      - name: Upload quick geiger report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: geiger-quick-report
          path: ./geiger-ark-wallet-cli.txt

  geiger-full:
    name: cargo-geiger-full
    runs-on: ubuntu-latest
    needs: geiger
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain-action@stable
      - name: Install cargo-geiger
        run: |
          cargo install cargo-geiger --version 0.27.0 || true
      - name: Run full cargo-geiger JSON scan
        run: |
          mkdir -p target/geiger
          # Run a full JSON output of cargo-geiger for the workspace
          cargo geiger --all-targets --format json > target/geiger/geiger-full.json || true
          # Also save a pretty-printed version for humans (optional)
          cargo geiger --all-targets > target/geiger/geiger-human.txt || true
      - name: Run extractor and produce concise report
        run: |
          python3 scripts/extract_geiger_cli.py || true
      - name: Upload geiger full artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: geiger-full-artifacts
          path: |
            target/geiger/geiger-full.json
            target/geiger/extract_cli.txt
            target/geiger/geiger-human.txt
